AWSTemplateFormatVersion: '2010-09-09'
Description: SNS to SQS Fan out example

################################################
# First Queue, subscription to Topic
################################################

Parameters:
  Prefix:
    Default: CodeCamp
    Description: Prefix used in Topic and Queue Names
    Type: String

Resources:
  # Topic
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      # Queue 1 subscription defined directly on Topic
      Subscription:
      - Endpoint: !GetAtt Queue1.Arn
        Protocol: sqs
      TopicName: !Sub ${Prefix}-Topic

  # Queues
  Queue1:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Prefix}-Queue1

  # Queue Policy to give Topic permission to write to Queues
  EventPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: QueuePolicy
        Version: '2012-10-17'
        Statement:
        - Action:
          - sqs:SendMessage
          Condition:
            ArnLike:
              aws:SourceArn: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${Prefix}-*'
          Effect: Allow
          Principal: '*'
          Resource: '*'
          Sid: Allow-SendMessage-To-Queues
      Queues:
      - !Ref Queue1

Outputs:
  Topic:
    Description: Topic Arn
    Value: !Ref Topic
  Queue1:
    Description: Queue 1 URL
    Value: !Ref Queue1
