AWSTemplateFormatVersion: '2010-09-09'
Description: SNS to SQS Fan out example

################################################
# Just the Topic
################################################

Parameters:
  Prefix:
    Default: CodeCamp
    Description: Prefix used in Topic and Queue Names
    Type: String

Resources:
  # Topic
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${Prefix}-Topic

Outputs:
  Topic:
    Description: Topic Arn
    Value: !Ref Topic
